add focus

diff --git a/.github/workflows/shared-workflow.yaml b/.github/workflows/shared-workflow.yaml
--- a/.github/workflows/shared-workflow.yaml
+++ b/.github/workflows/shared-workflow.yaml
@@ -8,11 +8,11 @@ on:
         type: string
       is_backend:
         required: false
-        default: 'false'
+        default: "false"
         type: string
       check_openapi:
         required: false
-        default: 'false'
+        default: "false"
         type: string
 
 jobs:
@@ -21,60 +21,63 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Use Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
-        cache: 'yarn'
+      - name: Use Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18"
+          cache: "yarn"
 
-    - name: Install dependencies
-      run: yarn workspaces focus ${{ inputs.package-name }}
+      - name: Install dependencies
+        run: yarn workspaces focus ${{ inputs.package-name }}
 
-    - name: Prisma generate
-      if: ${{ inputs.is_backend == 'true' }}
-      run: yarn workspace backend-lib prisma generate
+      - name: Prisma generate
+        if: ${{ inputs.is_backend == 'true' }}
+        run: yarn workspace backend-lib prisma generate
 
-    - name: Run lint
-      run: yarn workspace ${{ inputs.package-name }} lint
+      - name: Run lint
+        run: yarn workspace ${{ inputs.package-name }} lint
 
-    - name: Run Typecheck
-      run: yarn workspace ${{ inputs.package-name }} check
+      - name: Run Typecheck
+        run: yarn workspace ${{ inputs.package-name }} check
 
   open_api_check:
     name: Run Open API Check
     if: ${{ inputs.check_openapi == 'true' }}
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Use Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
-        cache: 'yarn'
+      - name: Use Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18"
+          cache: "yarn"
 
-    - name: Start API server
-      run: nohup yarn workspace api dev &
+      - name: Install dependencies
+        run: yarn workspaces focus ${{ inputs.package-name }}
 
-    - name: Check if Open API documentation needs updating
-      run: |
-        timeout=120 # Timeout in seconds
-        end=$((SECONDS+timeout))
-        while true; do
-          if curl -s -o /dev/null -w "%{http_code}" "http://localhost:3001/documentation/json" | grep -q "200"; then
-            curl "http://localhost:3001/documentation/json" | jq "." > packages/docs/open-api.json
-            git diff --quiet packages/docs/open-api.json || { echo >&2 "Error: Please update open-api.json file by running: 
-            curl 'http://localhost:3001/documentation/json' | jq '.' > packages/docs/open-api.json"; exit 1; }
-            break
-          elif [ $SECONDS -ge $end ]; then
-            echo "Timeout reached, exiting..."
-            exit 1
-          else
-            echo "Waiting for API server to be up..."
-            sleep 2
-          fi
-        done
+      - name: Start API server
+        run: nohup yarn workspace api dev &
+
+      - name: Check if Open API documentation needs updating
+        run: |
+          timeout=120 # Timeout in seconds
+          end=$((SECONDS+timeout))
+          while true; do
+            if curl -s -o /dev/null -w "%{http_code}" "http://localhost:3001/documentation/json" | grep -q "200"; then
+              curl "http://localhost:3001/documentation/json" | jq "." > packages/docs/open-api.json
+              git diff --quiet packages/docs/open-api.json || { echo >&2 "Error: Please update open-api.json file by running:
+              curl 'http://localhost:3001/documentation/json' | jq '.' > packages/docs/open-api.json"; exit 1; }
+              break
+            elif [ $SECONDS -ge $end ]; then
+              echo "Timeout reached, exiting..."
+              exit 1
+            else
+              echo "Waiting for API server to be up..."
+              sleep 2
+            fi
+          done
