fix: add timeout

diff --git a/.github/workflows/shared-workflow.yaml b/.github/workflows/shared-workflow.yaml
--- a/.github/workflows/shared-workflow.yaml
+++ b/.github/workflows/shared-workflow.yaml
@@ -51,10 +51,19 @@ jobs:
     - name: Check if Open API documentation needs updating
       if: ${{ inputs.check_openapi == 'true' }}
       run: |
-       until curl -s -o /dev/null -w "%{http_code}" "http://localhost:3001/documentation/json" | grep -q "200"; do
-       echo "Waiting for API server to be up..."
-       sleep 2
-       done
-       curl "http://localhost:3001/documentation/json" | jq "." > packages/docs/open-api.json
-       git diff --quiet packages/docs/open-api.json || { echo >&2 "Error: Please update open-api.json file by running: 
-       curl 'http://localhost:3001/documentation/json' | jq '.' > packages/docs/open-api.json"; exit 1; }
+        timeout=120 # Timeout in seconds
+        end=$((SECONDS+timeout))
+        while true; do
+          if curl -s -o /dev/null -w "%{http_code}" "http://localhost:3001/documentation/json" | grep -q "200"; then
+            curl "http://localhost:3001/documentation/json" | jq "." > packages/docs/open-api.json
+            git diff --quiet packages/docs/open-api.json || { echo >&2 "Error: Please update open-api.json file by running: 
+            curl 'http://localhost:3001/documentation/json' | jq '.' > packages/docs/open-api.json"; exit 1; }
+            break
+          elif [ $SECONDS -ge $end ]; then
+            echo "Timeout reached, exiting..."
+            exit 1
+          else
+            echo "Waiting for API server to be up..."
+            sleep 2
+          fi
+        done
